name: Deploy Bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # maquina que vai rodar
    steps:
      - uses: actions/checkout@v2 # Action do proprio github - copia o código para maquina
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Deploy
        run: |
          python aula2/github_actions/deploy.py